name: Create or Update Repo

env:
  GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repository to create or update'
        required: true
        type: string
      is_public_repo:
        description: 'Should the repository be public?'
        required: true
        type: boolean
        default: false
      package_import_name:
        description: Used in import statements, e.g., `import <package_import_name>`
        required: true
        type: string




jobs:
  create-repo-if-not-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: sunil-ytla
          IS_PUBLIC: ${{ github.event.inputs.is_public_repo }}
        run: |
          bash run.sh create-repo-if-not-exists

  configure-repo:
    needs:
      - create-repo-if-not-exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - run: |
          bash run.sh configure-repo
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: sunil-ytla

  open-pr-with-generated-project:
    needs:
      - create-repo-if-not-exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - run: |
          bash run.sh open-pr-with-generated-project
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: sunil-ytla
          PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
